package org.lwjgl.openal;

import java.util.Set;
import java.util.function.IntFunction;
import org.lwjgl.PointerBuffer;
import org.lwjgl.system.Checks;
import org.lwjgl.system.FunctionProvider;
import org.lwjgl.system.ThreadLocalUtil;

public final class ALCapabilities {
   public final long alGetError;
   public final long alGetErrorDirect;
   public final long alEnable;
   public final long alEnableDirect;
   public final long alDisable;
   public final long alDisableDirect;
   public final long alIsEnabled;
   public final long alIsEnabledDirect;
   public final long alGetBoolean;
   public final long alGetBooleanDirect;
   public final long alGetInteger;
   public final long alGetIntegerDirect;
   public final long alGetFloat;
   public final long alGetFloatDirect;
   public final long alGetDouble;
   public final long alGetDoubleDirect;
   public final long alGetBooleanv;
   public final long alGetBooleanvDirect;
   public final long alGetIntegerv;
   public final long alGetIntegervDirect;
   public final long alGetFloatv;
   public final long alGetFloatvDirect;
   public final long alGetDoublev;
   public final long alGetDoublevDirect;
   public final long alGetString;
   public final long alGetStringDirect;
   public final long alDistanceModel;
   public final long alDistanceModelDirect;
   public final long alDopplerFactor;
   public final long alDopplerFactorDirect;
   public final long alDopplerVelocity;
   public final long alListenerf;
   public final long alListenerfDirect;
   public final long alListeneri;
   public final long alListeneriDirect;
   public final long alListener3f;
   public final long alListener3fDirect;
   public final long alListenerfv;
   public final long alListenerfvDirect;
   public final long alGetListenerf;
   public final long alGetListenerfDirect;
   public final long alGetListeneri;
   public final long alGetListeneriDirect;
   public final long alGetListener3f;
   public final long alGetListener3fDirect;
   public final long alGetListenerfv;
   public final long alGetListenerfvDirect;
   public final long alGenSources;
   public final long alGenSourcesDirect;
   public final long alDeleteSources;
   public final long alDeleteSourcesDirect;
   public final long alIsSource;
   public final long alIsSourceDirect;
   public final long alSourcef;
   public final long alSourcefDirect;
   public final long alSource3f;
   public final long alSource3fDirect;
   public final long alSourcefv;
   public final long alSourcefvDirect;
   public final long alSourcei;
   public final long alSourceiDirect;
   public final long alGetSourcef;
   public final long alGetSourcefDirect;
   public final long alGetSource3f;
   public final long alGetSource3fDirect;
   public final long alGetSourcefv;
   public final long alGetSourcefvDirect;
   public final long alGetSourcei;
   public final long alGetSourceiDirect;
   public final long alGetSourceiv;
   public final long alGetSourceivDirect;
   public final long alSourceQueueBuffers;
   public final long alSourceQueueBuffersDirect;
   public final long alSourceUnqueueBuffers;
   public final long alSourceUnqueueBuffersDirect;
   public final long alSourcePlay;
   public final long alSourcePlayDirect;
   public final long alSourcePause;
   public final long alSourcePauseDirect;
   public final long alSourceStop;
   public final long alSourceStopDirect;
   public final long alSourceRewind;
   public final long alSourceRewindDirect;
   public final long alSourcePlayv;
   public final long alSourcePlayvDirect;
   public final long alSourcePausev;
   public final long alSourcePausevDirect;
   public final long alSourceStopv;
   public final long alSourceStopvDirect;
   public final long alSourceRewindv;
   public final long alSourceRewindvDirect;
   public final long alGenBuffers;
   public final long alGenBuffersDirect;
   public final long alDeleteBuffers;
   public final long alDeleteBuffersDirect;
   public final long alIsBuffer;
   public final long alIsBufferDirect;
   public final long alGetBufferf;
   public final long alGetBufferfDirect;
   public final long alGetBufferi;
   public final long alGetBufferiDirect;
   public final long alBufferData;
   public final long alBufferDataDirect;
   public final long alGetEnumValue;
   public final long alGetEnumValueDirect;
   public final long alGetProcAddress;
   public final long alGetProcAddressDirect;
   public final long alIsExtensionPresent;
   public final long alIsExtensionPresentDirect;
   public final long alListener3i;
   public final long alListener3iDirect;
   public final long alGetListener3i;
   public final long alGetListener3iDirect;
   public final long alGetListeneriv;
   public final long alGetListenerivDirect;
   public final long alSource3i;
   public final long alSource3iDirect;
   public final long alGetSource3i;
   public final long alGetSource3iDirect;
   public final long alListeneriv;
   public final long alListenerivDirect;
   public final long alSourceiv;
   public final long alSourceivDirect;
   public final long alBufferf;
   public final long alBufferfDirect;
   public final long alBuffer3f;
   public final long alBuffer3fDirect;
   public final long alBufferfv;
   public final long alBufferfvDirect;
   public final long alBufferi;
   public final long alBufferiDirect;
   public final long alBuffer3i;
   public final long alBuffer3iDirect;
   public final long alBufferiv;
   public final long alBufferivDirect;
   public final long alGetBuffer3i;
   public final long alGetBuffer3iDirect;
   public final long alGetBufferiv;
   public final long alGetBufferivDirect;
   public final long alGetBuffer3f;
   public final long alGetBuffer3fDirect;
   public final long alGetBufferfv;
   public final long alGetBufferfvDirect;
   public final long alSpeedOfSound;
   public final long alSpeedOfSoundDirect;
   public final long alDebugMessageCallbackEXT;
   public final long alDebugMessageCallbackDirectEXT;
   public final long alDebugMessageInsertEXT;
   public final long alDebugMessageInsertDirectEXT;
   public final long alDebugMessageControlEXT;
   public final long alDebugMessageControlDirectEXT;
   public final long alPushDebugGroupEXT;
   public final long alPushDebugGroupDirectEXT;
   public final long alPopDebugGroupEXT;
   public final long alPopDebugGroupDirectEXT;
   public final long alGetDebugMessageLogEXT;
   public final long alGetDebugMessageLogDirectEXT;
   public final long alObjectLabelEXT;
   public final long alObjectLabelDirectEXT;
   public final long alGetObjectLabelEXT;
   public final long alGetObjectLabelDirectEXT;
   public final long alGetPointerEXT;
   public final long alGetPointerDirectEXT;
   public final long alGetPointervEXT;
   public final long alGetPointervDirectEXT;
   public final long alGenEffects;
   public final long alGenEffectsDirect;
   public final long alDeleteEffects;
   public final long alDeleteEffectsDirect;
   public final long alIsEffect;
   public final long alIsEffectDirect;
   public final long alEffecti;
   public final long alEffectiDirect;
   public final long alEffectiv;
   public final long alEffectivDirect;
   public final long alEffectf;
   public final long alEffectfDirect;
   public final long alEffectfv;
   public final long alEffectfvDirect;
   public final long alGetEffecti;
   public final long alGetEffectiDirect;
   public final long alGetEffectiv;
   public final long alGetEffectivDirect;
   public final long alGetEffectf;
   public final long alGetEffectfDirect;
   public final long alGetEffectfv;
   public final long alGetEffectfvDirect;
   public final long alGenFilters;
   public final long alGenFiltersDirect;
   public final long alDeleteFilters;
   public final long alDeleteFiltersDirect;
   public final long alIsFilter;
   public final long alIsFilterDirect;
   public final long alFilteri;
   public final long alFilteriDirect;
   public final long alFilteriv;
   public final long alFilterivDirect;
   public final long alFilterf;
   public final long alFilterfDirect;
   public final long alFilterfv;
   public final long alFilterfvDirect;
   public final long alGetFilteri;
   public final long alGetFilteriDirect;
   public final long alGetFilteriv;
   public final long alGetFilterivDirect;
   public final long alGetFilterf;
   public final long alGetFilterfDirect;
   public final long alGetFilterfv;
   public final long alGetFilterfvDirect;
   public final long alGenAuxiliaryEffectSlots;
   public final long alGenAuxiliaryEffectSlotsDirect;
   public final long alDeleteAuxiliaryEffectSlots;
   public final long alDeleteAuxiliaryEffectSlotsDirect;
   public final long alIsAuxiliaryEffectSlot;
   public final long alIsAuxiliaryEffectSlotDirect;
   public final long alAuxiliaryEffectSloti;
   public final long alAuxiliaryEffectSlotiDirect;
   public final long alAuxiliaryEffectSlotiv;
   public final long alAuxiliaryEffectSlotivDirect;
   public final long alAuxiliaryEffectSlotf;
   public final long alAuxiliaryEffectSlotfDirect;
   public final long alAuxiliaryEffectSlotfv;
   public final long alAuxiliaryEffectSlotfvDirect;
   public final long alGetAuxiliaryEffectSloti;
   public final long alGetAuxiliaryEffectSlotiDirect;
   public final long alGetAuxiliaryEffectSlotiv;
   public final long alGetAuxiliaryEffectSlotivDirect;
   public final long alGetAuxiliaryEffectSlotf;
   public final long alGetAuxiliaryEffectSlotfDirect;
   public final long alGetAuxiliaryEffectSlotfv;
   public final long alGetAuxiliaryEffectSlotfvDirect;
   public final long alBufferDataStatic;
   public final long alBufferDataStaticDirect;
   public final long alBufferSamplesSOFT;
   public final long alBufferSubSamplesSOFT;
   public final long alGetBufferSamplesSOFT;
   public final long alIsBufferFormatSupportedSOFT;
   public final long alBufferSubDataSOFT;
   public final long alBufferSubDataDirectSOFT;
   public final long alBufferCallbackSOFT;
   public final long alBufferCallbackDirectSOFT;
   public final long alGetBufferPtrSOFT;
   public final long alGetBufferPtrDirectSOFT;
   public final long alGetBuffer3PtrSOFT;
   public final long alGetBuffer3PtrDirectSOFT;
   public final long alGetBufferPtrvSOFT;
   public final long alGetBufferPtrvDirectSOFT;
   public final long alDeferUpdatesSOFT;
   public final long alDeferUpdatesDirectSOFT;
   public final long alProcessUpdatesSOFT;
   public final long alProcessUpdatesDirectSOFT;
   public final long alEventControlSOFT;
   public final long alEventControlDirectSOFT;
   public final long alEventCallbackSOFT;
   public final long alEventCallbackDirectSOFT;
   public final long alGetPointerSOFT;
   public final long alGetPointerDirectSOFT;
   public final long alGetPointervSOFT;
   public final long alGetPointervDirectSOFT;
   public final long alSourcedSOFT;
   public final long alSourcedDirectSOFT;
   public final long alSource3dSOFT;
   public final long alSource3dDirectSOFT;
   public final long alSourcedvSOFT;
   public final long alSourcedvDirectSOFT;
   public final long alGetSourcedSOFT;
   public final long alGetSourcedDirectSOFT;
   public final long alGetSource3dSOFT;
   public final long alGetSource3dDirectSOFT;
   public final long alGetSourcedvSOFT;
   public final long alGetSourcedvDirectSOFT;
   public final long alSourcei64SOFT;
   public final long alSourcei64DirectSOFT;
   public final long alSource3i64SOFT;
   public final long alSource3i64DirectSOFT;
   public final long alSourcei64vSOFT;
   public final long alSourcei64vDirectSOFT;
   public final long alGetSourcei64SOFT;
   public final long alGetSourcei64DirectSOFT;
   public final long alGetSource3i64SOFT;
   public final long alGetSource3i64DirectSOFT;
   public final long alGetSourcei64vSOFT;
   public final long alGetSourcei64vDirectSOFT;
   public final long alGetStringiSOFT;
   public final long alGetStringiDirectSOFT;
   public final long alSourcePlayAtTimeSOFT;
   public final long alSourcePlayAtTimeDirectSOFT;
   public final long alSourcePlayAtTimevSOFT;
   public final long alSourcePlayAtTimevDirectSOFT;
   public final boolean OpenAL10;
   public final boolean OpenAL11;
   public final boolean AL_EXT_ALAW;
   public final boolean AL_EXT_BFORMAT;
   public final boolean AL_EXT_debug;
   public final boolean AL_EXT_direct_context;
   public final boolean AL_EXT_DOUBLE;
   public final boolean ALC_EXT_EFX;
   public final boolean AL_EXT_EXPONENT_DISTANCE;
   public final boolean AL_EXT_FLOAT32;
   public final boolean AL_EXT_IMA4;
   public final boolean AL_EXT_LINEAR_DISTANCE;
   public final boolean AL_EXT_MCFORMATS;
   public final boolean AL_EXT_MULAW;
   public final boolean AL_EXT_MULAW_BFORMAT;
   public final boolean AL_EXT_MULAW_MCFORMATS;
   public final boolean AL_EXT_OFFSET;
   public final boolean AL_EXT_source_distance_model;
   public final boolean AL_EXT_SOURCE_RADIUS;
   public final boolean AL_EXT_STATIC_BUFFER;
   public final boolean AL_EXT_STEREO_ANGLES;
   public final boolean AL_EXT_vorbis;
   public final boolean AL_LOKI_IMA_ADPCM;
   public final boolean AL_LOKI_quadriphonic;
   public final boolean AL_LOKI_WAVE_format;
   public final boolean AL_SOFT_bformat_ex;
   public final boolean AL_SOFT_block_alignment;
   public final boolean AL_SOFT_buffer_length_query;
   public final boolean AL_SOFT_buffer_samples;
   public final boolean AL_SOFT_buffer_sub_data;
   public final boolean AL_SOFT_callback_buffer;
   public final boolean AL_SOFT_deferred_updates;
   public final boolean AL_SOFT_direct_channels;
   public final boolean AL_SOFT_direct_channels_remix;
   public final boolean AL_SOFT_effect_target;
   public final boolean AL_SOFT_events;
   public final boolean AL_SOFT_gain_clamp_ex;
   public final boolean AL_SOFT_loop_points;
   public final boolean AL_SOFT_MSADPCM;
   public final boolean AL_SOFT_source_latency;
   public final boolean AL_SOFT_source_length;
   public final boolean AL_SOFT_source_resampler;
   public final boolean AL_SOFT_source_spatialize;
   public final boolean AL_SOFT_source_start_delay;
   public final boolean AL_SOFT_UHJ;
   public final boolean AL_SOFT_UHJ_ex;
   public final boolean AL_SOFTX_hold_on_disconnect;
   final PointerBuffer addresses;

   public ALCapabilities(FunctionProvider var1, Set var2, IntFunction var3) {
      super();
      FunctionProvider var10000 = var1;
      FunctionProvider var10001 = var1;
      FunctionProvider var10002 = var1;
      FunctionProvider var10003 = var1;
      FunctionProvider var10004 = var1;
      FunctionProvider var10005 = var1;
      FunctionProvider var10006 = var1;
      FunctionProvider var10007 = var1;
      FunctionProvider var10008 = var1;
      FunctionProvider var10009 = var1;
      FunctionProvider var10010 = var1;
      FunctionProvider var10011 = var1;
      PointerBuffer var4;
      this.OpenAL10 = check_AL10(var1, var4 = (PointerBuffer)var3.apply(289), var2);
      this.OpenAL11 = check_AL11(var10011, var4, var2);
      this.AL_EXT_ALAW = var2.contains("AL_EXT_ALAW");
      this.AL_EXT_BFORMAT = var2.contains("AL_EXT_BFORMAT");
      this.AL_EXT_debug = check_EXT_debug(var10010, var4, var2);
      this.AL_EXT_direct_context = var2.contains("AL_EXT_direct_context");
      this.AL_EXT_DOUBLE = var2.contains("AL_EXT_DOUBLE");
      this.ALC_EXT_EFX = check_EXT_EFX(var10009, var4, var2);
      this.AL_EXT_EXPONENT_DISTANCE = var2.contains("AL_EXT_EXPONENT_DISTANCE");
      this.AL_EXT_FLOAT32 = var2.contains("AL_EXT_FLOAT32");
      this.AL_EXT_IMA4 = var2.contains("AL_EXT_IMA4");
      this.AL_EXT_LINEAR_DISTANCE = var2.contains("AL_EXT_LINEAR_DISTANCE");
      this.AL_EXT_MCFORMATS = var2.contains("AL_EXT_MCFORMATS");
      this.AL_EXT_MULAW = var2.contains("AL_EXT_MULAW");
      this.AL_EXT_MULAW_BFORMAT = var2.contains("AL_EXT_MULAW_BFORMAT");
      this.AL_EXT_MULAW_MCFORMATS = var2.contains("AL_EXT_MULAW_MCFORMATS");
      this.AL_EXT_OFFSET = var2.contains("AL_EXT_OFFSET");
      this.AL_EXT_source_distance_model = var2.contains("AL_EXT_source_distance_model");
      this.AL_EXT_SOURCE_RADIUS = var2.contains("AL_EXT_SOURCE_RADIUS");
      this.AL_EXT_STATIC_BUFFER = check_EXT_STATIC_BUFFER(var10008, var4, var2);
      this.AL_EXT_STEREO_ANGLES = var2.contains("AL_EXT_STEREO_ANGLES");
      this.AL_EXT_vorbis = var2.contains("AL_EXT_vorbis");
      this.AL_LOKI_IMA_ADPCM = var2.contains("AL_LOKI_IMA_ADPCM");
      this.AL_LOKI_quadriphonic = var2.contains("AL_LOKI_quadriphonic");
      this.AL_LOKI_WAVE_format = var2.contains("AL_LOKI_WAVE_format");
      this.AL_SOFT_bformat_ex = var2.contains("AL_SOFT_bformat_ex");
      this.AL_SOFT_block_alignment = var2.contains("AL_SOFT_block_alignment");
      this.AL_SOFT_buffer_length_query = var2.contains("AL_SOFT_buffer_length_query");
      this.AL_SOFT_buffer_samples = check_SOFT_buffer_samples(var10007, var4, var2);
      this.AL_SOFT_buffer_sub_data = check_SOFT_buffer_sub_data(var10006, var4, var2);
      this.AL_SOFT_callback_buffer = check_SOFT_callback_buffer(var10005, var4, var2);
      this.AL_SOFT_deferred_updates = check_SOFT_deferred_updates(var10004, var4, var2);
      this.AL_SOFT_direct_channels = var2.contains("AL_SOFT_direct_channels");
      this.AL_SOFT_direct_channels_remix = var2.contains("AL_SOFT_direct_channels_remix");
      this.AL_SOFT_effect_target = var2.contains("AL_SOFT_effect_target");
      this.AL_SOFT_events = check_SOFT_events(var10003, var4, var2);
      this.AL_SOFT_gain_clamp_ex = var2.contains("AL_SOFT_gain_clamp_ex");
      this.AL_SOFT_loop_points = var2.contains("AL_SOFT_loop_points");
      this.AL_SOFT_MSADPCM = var2.contains("AL_SOFT_MSADPCM");
      this.AL_SOFT_source_latency = check_SOFT_source_latency(var10002, var4, var2);
      this.AL_SOFT_source_length = var2.contains("AL_SOFT_source_length");
      this.AL_SOFT_source_resampler = check_SOFT_source_resampler(var10001, var4, var2);
      this.AL_SOFT_source_spatialize = var2.contains("AL_SOFT_source_spatialize");
      this.AL_SOFT_source_start_delay = check_SOFT_source_start_delay(var10000, var4, var2);
      this.AL_SOFT_UHJ = var2.contains("AL_SOFT_UHJ");
      this.AL_SOFT_UHJ_ex = var2.contains("AL_SOFT_UHJ_ex");
      this.AL_SOFTX_hold_on_disconnect = var2.contains("AL_SOFTX_hold_on_disconnect");
      long var5 = var4.get(0);
      this.alGetError = var5;
      var5 = var4.get(1);
      this.alGetErrorDirect = var5;
      var5 = var4.get(2);
      this.alEnable = var5;
      var5 = var4.get(3);
      this.alEnableDirect = var5;
      var5 = var4.get(4);
      this.alDisable = var5;
      var5 = var4.get(5);
      this.alDisableDirect = var5;
      var5 = var4.get(6);
      this.alIsEnabled = var5;
      var5 = var4.get(7);
      this.alIsEnabledDirect = var5;
      var5 = var4.get(8);
      this.alGetBoolean = var5;
      var5 = var4.get(9);
      this.alGetBooleanDirect = var5;
      var5 = var4.get(10);
      this.alGetInteger = var5;
      var5 = var4.get(11);
      this.alGetIntegerDirect = var5;
      var5 = var4.get(12);
      this.alGetFloat = var5;
      var5 = var4.get(13);
      this.alGetFloatDirect = var5;
      var5 = var4.get(14);
      this.alGetDouble = var5;
      var5 = var4.get(15);
      this.alGetDoubleDirect = var5;
      var5 = var4.get(16);
      this.alGetBooleanv = var5;
      var5 = var4.get(17);
      this.alGetBooleanvDirect = var5;
      var5 = var4.get(18);
      this.alGetIntegerv = var5;
      var5 = var4.get(19);
      this.alGetIntegervDirect = var5;
      var5 = var4.get(20);
      this.alGetFloatv = var5;
      var5 = var4.get(21);
      this.alGetFloatvDirect = var5;
      var5 = var4.get(22);
      this.alGetDoublev = var5;
      var5 = var4.get(23);
      this.alGetDoublevDirect = var5;
      var5 = var4.get(24);
      this.alGetString = var5;
      var5 = var4.get(25);
      this.alGetStringDirect = var5;
      var5 = var4.get(26);
      this.alDistanceModel = var5;
      var5 = var4.get(27);
      this.alDistanceModelDirect = var5;
      var5 = var4.get(28);
      this.alDopplerFactor = var5;
      var5 = var4.get(29);
      this.alDopplerFactorDirect = var5;
      var5 = var4.get(30);
      this.alDopplerVelocity = var5;
      var5 = var4.get(31);
      this.alListenerf = var5;
      var5 = var4.get(32);
      this.alListenerfDirect = var5;
      var5 = var4.get(33);
      this.alListeneri = var5;
      var5 = var4.get(34);
      this.alListeneriDirect = var5;
      var5 = var4.get(35);
      this.alListener3f = var5;
      var5 = var4.get(36);
      this.alListener3fDirect = var5;
      var5 = var4.get(37);
      this.alListenerfv = var5;
      var5 = var4.get(38);
      this.alListenerfvDirect = var5;
      var5 = var4.get(39);
      this.alGetListenerf = var5;
      var5 = var4.get(40);
      this.alGetListenerfDirect = var5;
      var5 = var4.get(41);
      this.alGetListeneri = var5;
      var5 = var4.get(42);
      this.alGetListeneriDirect = var5;
      var5 = var4.get(43);
      this.alGetListener3f = var5;
      var5 = var4.get(44);
      this.alGetListener3fDirect = var5;
      var5 = var4.get(45);
      this.alGetListenerfv = var5;
      var5 = var4.get(46);
      this.alGetListenerfvDirect = var5;
      var5 = var4.get(47);
      this.alGenSources = var5;
      var5 = var4.get(48);
      this.alGenSourcesDirect = var5;
      var5 = var4.get(49);
      this.alDeleteSources = var5;
      var5 = var4.get(50);
      this.alDeleteSourcesDirect = var5;
      var5 = var4.get(51);
      this.alIsSource = var5;
      var5 = var4.get(52);
      this.alIsSourceDirect = var5;
      var5 = var4.get(53);
      this.alSourcef = var5;
      var5 = var4.get(54);
      this.alSourcefDirect = var5;
      var5 = var4.get(55);
      this.alSource3f = var5;
      var5 = var4.get(56);
      this.alSource3fDirect = var5;
      var5 = var4.get(57);
      this.alSourcefv = var5;
      var5 = var4.get(58);
      this.alSourcefvDirect = var5;
      var5 = var4.get(59);
      this.alSourcei = var5;
      var5 = var4.get(60);
      this.alSourceiDirect = var5;
      var5 = var4.get(61);
      this.alGetSourcef = var5;
      var5 = var4.get(62);
      this.alGetSourcefDirect = var5;
      var5 = var4.get(63);
      this.alGetSource3f = var5;
      var5 = var4.get(64);
      this.alGetSource3fDirect = var5;
      var5 = var4.get(65);
      this.alGetSourcefv = var5;
      var5 = var4.get(66);
      this.alGetSourcefvDirect = var5;
      var5 = var4.get(67);
      this.alGetSourcei = var5;
      var5 = var4.get(68);
      this.alGetSourceiDirect = var5;
      var5 = var4.get(69);
      this.alGetSourceiv = var5;
      var5 = var4.get(70);
      this.alGetSourceivDirect = var5;
      var5 = var4.get(71);
      this.alSourceQueueBuffers = var5;
      var5 = var4.get(72);
      this.alSourceQueueBuffersDirect = var5;
      var5 = var4.get(73);
      this.alSourceUnqueueBuffers = var5;
      var5 = var4.get(74);
      this.alSourceUnqueueBuffersDirect = var5;
      var5 = var4.get(75);
      this.alSourcePlay = var5;
      var5 = var4.get(76);
      this.alSourcePlayDirect = var5;
      var5 = var4.get(77);
      this.alSourcePause = var5;
      var5 = var4.get(78);
      this.alSourcePauseDirect = var5;
      var5 = var4.get(79);
      this.alSourceStop = var5;
      var5 = var4.get(80);
      this.alSourceStopDirect = var5;
      var5 = var4.get(81);
      this.alSourceRewind = var5;
      var5 = var4.get(82);
      this.alSourceRewindDirect = var5;
      var5 = var4.get(83);
      this.alSourcePlayv = var5;
      var5 = var4.get(84);
      this.alSourcePlayvDirect = var5;
      var5 = var4.get(85);
      this.alSourcePausev = var5;
      var5 = var4.get(86);
      this.alSourcePausevDirect = var5;
      var5 = var4.get(87);
      this.alSourceStopv = var5;
      var5 = var4.get(88);
      this.alSourceStopvDirect = var5;
      var5 = var4.get(89);
      this.alSourceRewindv = var5;
      var5 = var4.get(90);
      this.alSourceRewindvDirect = var5;
      var5 = var4.get(91);
      this.alGenBuffers = var5;
      var5 = var4.get(92);
      this.alGenBuffersDirect = var5;
      var5 = var4.get(93);
      this.alDeleteBuffers = var5;
      var5 = var4.get(94);
      this.alDeleteBuffersDirect = var5;
      var5 = var4.get(95);
      this.alIsBuffer = var5;
      var5 = var4.get(96);
      this.alIsBufferDirect = var5;
      var5 = var4.get(97);
      this.alGetBufferf = var5;
      var5 = var4.get(98);
      this.alGetBufferfDirect = var5;
      var5 = var4.get(99);
      this.alGetBufferi = var5;
      var5 = var4.get(100);
      this.alGetBufferiDirect = var5;
      var5 = var4.get(101);
      this.alBufferData = var5;
      var5 = var4.get(102);
      this.alBufferDataDirect = var5;
      var5 = var4.get(103);
      this.alGetEnumValue = var5;
      var5 = var4.get(104);
      this.alGetEnumValueDirect = var5;
      var5 = var4.get(105);
      this.alGetProcAddress = var5;
      var5 = var4.get(106);
      this.alGetProcAddressDirect = var5;
      var5 = var4.get(107);
      this.alIsExtensionPresent = var5;
      var5 = var4.get(108);
      this.alIsExtensionPresentDirect = var5;
      var5 = var4.get(109);
      this.alListener3i = var5;
      var5 = var4.get(110);
      this.alListener3iDirect = var5;
      var5 = var4.get(111);
      this.alGetListener3i = var5;
      var5 = var4.get(112);
      this.alGetListener3iDirect = var5;
      var5 = var4.get(113);
      this.alGetListeneriv = var5;
      var5 = var4.get(114);
      this.alGetListenerivDirect = var5;
      var5 = var4.get(115);
      this.alSource3i = var5;
      var5 = var4.get(116);
      this.alSource3iDirect = var5;
      var5 = var4.get(117);
      this.alGetSource3i = var5;
      var5 = var4.get(118);
      this.alGetSource3iDirect = var5;
      var5 = var4.get(119);
      this.alListeneriv = var5;
      var5 = var4.get(120);
      this.alListenerivDirect = var5;
      var5 = var4.get(121);
      this.alSourceiv = var5;
      var5 = var4.get(122);
      this.alSourceivDirect = var5;
      var5 = var4.get(123);
      this.alBufferf = var5;
      var5 = var4.get(124);
      this.alBufferfDirect = var5;
      var5 = var4.get(125);
      this.alBuffer3f = var5;
      var5 = var4.get(126);
      this.alBuffer3fDirect = var5;
      var5 = var4.get(127);
      this.alBufferfv = var5;
      var5 = var4.get(128);
      this.alBufferfvDirect = var5;
      var5 = var4.get(129);
      this.alBufferi = var5;
      var5 = var4.get(130);
      this.alBufferiDirect = var5;
      var5 = var4.get(131);
      this.alBuffer3i = var5;
      var5 = var4.get(132);
      this.alBuffer3iDirect = var5;
      var5 = var4.get(133);
      this.alBufferiv = var5;
      var5 = var4.get(134);
      this.alBufferivDirect = var5;
      var5 = var4.get(135);
      this.alGetBuffer3i = var5;
      var5 = var4.get(136);
      this.alGetBuffer3iDirect = var5;
      var5 = var4.get(137);
      this.alGetBufferiv = var5;
      var5 = var4.get(138);
      this.alGetBufferivDirect = var5;
      var5 = var4.get(139);
      this.alGetBuffer3f = var5;
      var5 = var4.get(140);
      this.alGetBuffer3fDirect = var5;
      var5 = var4.get(141);
      this.alGetBufferfv = var5;
      var5 = var4.get(142);
      this.alGetBufferfvDirect = var5;
      var5 = var4.get(143);
      this.alSpeedOfSound = var5;
      var5 = var4.get(144);
      this.alSpeedOfSoundDirect = var5;
      var5 = var4.get(145);
      this.alDebugMessageCallbackEXT = var5;
      var5 = var4.get(146);
      this.alDebugMessageCallbackDirectEXT = var5;
      var5 = var4.get(147);
      this.alDebugMessageInsertEXT = var5;
      var5 = var4.get(148);
      this.alDebugMessageInsertDirectEXT = var5;
      var5 = var4.get(149);
      this.alDebugMessageControlEXT = var5;
      var5 = var4.get(150);
      this.alDebugMessageControlDirectEXT = var5;
      var5 = var4.get(151);
      this.alPushDebugGroupEXT = var5;
      var5 = var4.get(152);
      this.alPushDebugGroupDirectEXT = var5;
      var5 = var4.get(153);
      this.alPopDebugGroupEXT = var5;
      var5 = var4.get(154);
      this.alPopDebugGroupDirectEXT = var5;
      var5 = var4.get(155);
      this.alGetDebugMessageLogEXT = var5;
      var5 = var4.get(156);
      this.alGetDebugMessageLogDirectEXT = var5;
      var5 = var4.get(157);
      this.alObjectLabelEXT = var5;
      var5 = var4.get(158);
      this.alObjectLabelDirectEXT = var5;
      var5 = var4.get(159);
      this.alGetObjectLabelEXT = var5;
      var5 = var4.get(160);
      this.alGetObjectLabelDirectEXT = var5;
      var5 = var4.get(161);
      this.alGetPointerEXT = var5;
      var5 = var4.get(162);
      this.alGetPointerDirectEXT = var5;
      var5 = var4.get(163);
      this.alGetPointervEXT = var5;
      var5 = var4.get(164);
      this.alGetPointervDirectEXT = var5;
      var5 = var4.get(165);
      this.alGenEffects = var5;
      var5 = var4.get(166);
      this.alGenEffectsDirect = var5;
      var5 = var4.get(167);
      this.alDeleteEffects = var5;
      var5 = var4.get(168);
      this.alDeleteEffectsDirect = var5;
      var5 = var4.get(169);
      this.alIsEffect = var5;
      var5 = var4.get(170);
      this.alIsEffectDirect = var5;
      var5 = var4.get(171);
      this.alEffecti = var5;
      var5 = var4.get(172);
      this.alEffectiDirect = var5;
      var5 = var4.get(173);
      this.alEffectiv = var5;
      var5 = var4.get(174);
      this.alEffectivDirect = var5;
      var5 = var4.get(175);
      this.alEffectf = var5;
      var5 = var4.get(176);
      this.alEffectfDirect = var5;
      var5 = var4.get(177);
      this.alEffectfv = var5;
      var5 = var4.get(178);
      this.alEffectfvDirect = var5;
      var5 = var4.get(179);
      this.alGetEffecti = var5;
      var5 = var4.get(180);
      this.alGetEffectiDirect = var5;
      var5 = var4.get(181);
      this.alGetEffectiv = var5;
      var5 = var4.get(182);
      this.alGetEffectivDirect = var5;
      var5 = var4.get(183);
      this.alGetEffectf = var5;
      var5 = var4.get(184);
      this.alGetEffectfDirect = var5;
      var5 = var4.get(185);
      this.alGetEffectfv = var5;
      var5 = var4.get(186);
      this.alGetEffectfvDirect = var5;
      var5 = var4.get(187);
      this.alGenFilters = var5;
      var5 = var4.get(188);
      this.alGenFiltersDirect = var5;
      var5 = var4.get(189);
      this.alDeleteFilters = var5;
      var5 = var4.get(190);
      this.alDeleteFiltersDirect = var5;
      var5 = var4.get(191);
      this.alIsFilter = var5;
      var5 = var4.get(192);
      this.alIsFilterDirect = var5;
      var5 = var4.get(193);
      this.alFilteri = var5;
      var5 = var4.get(194);
      this.alFilteriDirect = var5;
      var5 = var4.get(195);
      this.alFilteriv = var5;
      var5 = var4.get(196);
      this.alFilterivDirect = var5;
      var5 = var4.get(197);
      this.alFilterf = var5;
      var5 = var4.get(198);
      this.alFilterfDirect = var5;
      var5 = var4.get(199);
      this.alFilterfv = var5;
      var5 = var4.get(200);
      this.alFilterfvDirect = var5;
      var5 = var4.get(201);
      this.alGetFilteri = var5;
      var5 = var4.get(202);
      this.alGetFilteriDirect = var5;
      var5 = var4.get(203);
      this.alGetFilteriv = var5;
      var5 = var4.get(204);
      this.alGetFilterivDirect = var5;
      var5 = var4.get(205);
      this.alGetFilterf = var5;
      var5 = var4.get(206);
      this.alGetFilterfDirect = var5;
      var5 = var4.get(207);
      this.alGetFilterfv = var5;
      var5 = var4.get(208);
      this.alGetFilterfvDirect = var5;
      var5 = var4.get(209);
      this.alGenAuxiliaryEffectSlots = var5;
      var5 = var4.get(210);
      this.alGenAuxiliaryEffectSlotsDirect = var5;
      var5 = var4.get(211);
      this.alDeleteAuxiliaryEffectSlots = var5;
      var5 = var4.get(212);
      this.alDeleteAuxiliaryEffectSlotsDirect = var5;
      var5 = var4.get(213);
      this.alIsAuxiliaryEffectSlot = var5;
      var5 = var4.get(214);
      this.alIsAuxiliaryEffectSlotDirect = var5;
      var5 = var4.get(215);
      this.alAuxiliaryEffectSloti = var5;
      var5 = var4.get(216);
      this.alAuxiliaryEffectSlotiDirect = var5;
      var5 = var4.get(217);
      this.alAuxiliaryEffectSlotiv = var5;
      var5 = var4.get(218);
      this.alAuxiliaryEffectSlotivDirect = var5;
      var5 = var4.get(219);
      this.alAuxiliaryEffectSlotf = var5;
      var5 = var4.get(220);
      this.alAuxiliaryEffectSlotfDirect = var5;
      var5 = var4.get(221);
      this.alAuxiliaryEffectSlotfv = var5;
      var5 = var4.get(222);
      this.alAuxiliaryEffectSlotfvDirect = var5;
      var5 = var4.get(223);
      this.alGetAuxiliaryEffectSloti = var5;
      var5 = var4.get(224);
      this.alGetAuxiliaryEffectSlotiDirect = var5;
      var5 = var4.get(225);
      this.alGetAuxiliaryEffectSlotiv = var5;
      var5 = var4.get(226);
      this.alGetAuxiliaryEffectSlotivDirect = var5;
      var5 = var4.get(227);
      this.alGetAuxiliaryEffectSlotf = var5;
      var5 = var4.get(228);
      this.alGetAuxiliaryEffectSlotfDirect = var5;
      var5 = var4.get(229);
      this.alGetAuxiliaryEffectSlotfv = var5;
      var5 = var4.get(230);
      this.alGetAuxiliaryEffectSlotfvDirect = var5;
      var5 = var4.get(231);
      this.alBufferDataStatic = var5;
      var5 = var4.get(232);
      this.alBufferDataStaticDirect = var5;
      var5 = var4.get(233);
      this.alBufferSamplesSOFT = var5;
      var5 = var4.get(234);
      this.alBufferSubSamplesSOFT = var5;
      var5 = var4.get(235);
      this.alGetBufferSamplesSOFT = var5;
      var5 = var4.get(236);
      this.alIsBufferFormatSupportedSOFT = var5;
      var5 = var4.get(237);
      this.alBufferSubDataSOFT = var5;
      var5 = var4.get(238);
      this.alBufferSubDataDirectSOFT = var5;
      var5 = var4.get(239);
      this.alBufferCallbackSOFT = var5;
      var5 = var4.get(240);
      this.alBufferCallbackDirectSOFT = var5;
      var5 = var4.get(241);
      this.alGetBufferPtrSOFT = var5;
      var5 = var4.get(242);
      this.alGetBufferPtrDirectSOFT = var5;
      var5 = var4.get(243);
      this.alGetBuffer3PtrSOFT = var5;
      var5 = var4.get(244);
      this.alGetBuffer3PtrDirectSOFT = var5;
      var5 = var4.get(245);
      this.alGetBufferPtrvSOFT = var5;
      var5 = var4.get(246);
      this.alGetBufferPtrvDirectSOFT = var5;
      var5 = var4.get(247);
      this.alDeferUpdatesSOFT = var5;
      var5 = var4.get(248);
      this.alDeferUpdatesDirectSOFT = var5;
      var5 = var4.get(249);
      this.alProcessUpdatesSOFT = var5;
      var5 = var4.get(250);
      this.alProcessUpdatesDirectSOFT = var5;
      var5 = var4.get(251);
      this.alEventControlSOFT = var5;
      var5 = var4.get(252);
      this.alEventControlDirectSOFT = var5;
      var5 = var4.get(253);
      this.alEventCallbackSOFT = var5;
      var5 = var4.get(254);
      this.alEventCallbackDirectSOFT = var5;
      var5 = var4.get(255);
      this.alGetPointerSOFT = var5;
      var5 = var4.get(256);
      this.alGetPointerDirectSOFT = var5;
      var5 = var4.get(257);
      this.alGetPointervSOFT = var5;
      var5 = var4.get(258);
      this.alGetPointervDirectSOFT = var5;
      var5 = var4.get(259);
      this.alSourcedSOFT = var5;
      var5 = var4.get(260);
      this.alSourcedDirectSOFT = var5;
      var5 = var4.get(261);
      this.alSource3dSOFT = var5;
      var5 = var4.get(262);
      this.alSource3dDirectSOFT = var5;
      var5 = var4.get(263);
      this.alSourcedvSOFT = var5;
      var5 = var4.get(264);
      this.alSourcedvDirectSOFT = var5;
      var5 = var4.get(265);
      this.alGetSourcedSOFT = var5;
      var5 = var4.get(266);
      this.alGetSourcedDirectSOFT = var5;
      var5 = var4.get(267);
      this.alGetSource3dSOFT = var5;
      var5 = var4.get(268);
      this.alGetSource3dDirectSOFT = var5;
      var5 = var4.get(269);
      this.alGetSourcedvSOFT = var5;
      var5 = var4.get(270);
      this.alGetSourcedvDirectSOFT = var5;
      var5 = var4.get(271);
      this.alSourcei64SOFT = var5;
      var5 = var4.get(272);
      this.alSourcei64DirectSOFT = var5;
      var5 = var4.get(273);
      this.alSource3i64SOFT = var5;
      var5 = var4.get(274);
      this.alSource3i64DirectSOFT = var5;
      var5 = var4.get(275);
      this.alSourcei64vSOFT = var5;
      var5 = var4.get(276);
      this.alSourcei64vDirectSOFT = var5;
      var5 = var4.get(277);
      this.alGetSourcei64SOFT = var5;
      var5 = var4.get(278);
      this.alGetSourcei64DirectSOFT = var5;
      var5 = var4.get(279);
      this.alGetSource3i64SOFT = var5;
      var5 = var4.get(280);
      this.alGetSource3i64DirectSOFT = var5;
      var5 = var4.get(281);
      this.alGetSourcei64vSOFT = var5;
      var5 = var4.get(282);
      this.alGetSourcei64vDirectSOFT = var5;
      var5 = var4.get(283);
      this.alGetStringiSOFT = var5;
      var5 = var4.get(284);
      this.alGetStringiDirectSOFT = var5;
      var5 = var4.get(285);
      this.alSourcePlayAtTimeSOFT = var5;
      var5 = var4.get(286);
      this.alSourcePlayAtTimeDirectSOFT = var5;
      var5 = var4.get(287);
      this.alSourcePlayAtTimevSOFT = var5;
      var5 = var4.get(288);
      this.alSourcePlayAtTimevDirectSOFT = var5;
      this.addresses = ThreadLocalUtil.setupAddressBuffer(var4);
   }

   private static boolean check_AL10(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("OpenAL10")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         (var3 = new int[109])[0] = 0;
         var3[1] = 1;
         var3[2] = 2;
         var3[3] = 3;
         var3[4] = 4;
         var3[5] = 5;
         var3[6] = 6;
         var3[7] = 7;
         var3[8] = 8;
         var3[9] = 9;
         var3[10] = 10;
         var3[11] = 11;
         var3[12] = 12;
         var3[13] = 13;
         var3[14] = 14;
         var3[15] = 15;
         var3[16] = 16;
         var3[17] = 17;
         var3[18] = 18;
         var3[19] = 19;
         var3[20] = 20;
         var3[21] = 21;
         var3[22] = 22;
         var3[23] = 23;
         var3[24] = 24;
         var3[25] = 25;
         var3[26] = 26;
         var3[27] = 27;
         var3[28] = 28;
         var3[29] = 29;
         var3[30] = 30;
         var3[31] = 31;
         var3[32] = 32;
         var3[33] = 33;
         var3[34] = 34;
         var3[35] = 35;
         var3[36] = 36;
         var3[37] = 37;
         var3[38] = 38;
         var3[39] = 39;
         var3[40] = 40;
         var3[41] = 41;
         var3[42] = 42;
         var3[43] = 43;
         var3[44] = 44;
         var3[45] = 45;
         var3[46] = 46;
         var3[47] = 47;
         var3[48] = 48;
         var3[49] = 49;
         var3[50] = 50;
         var3[51] = 51;
         var3[52] = 52;
         var3[53] = 53;
         var3[54] = 54;
         var3[55] = 55;
         var3[56] = 56;
         var3[57] = 57;
         var3[58] = 58;
         var3[59] = 59;
         var3[60] = 60;
         var3[61] = 61;
         var3[62] = 62;
         var3[63] = 63;
         var3[64] = 64;
         var3[65] = 65;
         var3[66] = 66;
         var3[67] = 67;
         var3[68] = 68;
         var3[69] = 69;
         var3[70] = 70;
         var3[71] = 71;
         var3[72] = 72;
         var3[73] = 73;
         var3[74] = 74;
         var3[75] = 75;
         var3[76] = 76;
         var3[77] = 77;
         var3[78] = 78;
         var3[79] = 79;
         var3[80] = 80;
         var3[81] = 81;
         var3[82] = 82;
         var3[83] = 83;
         var3[84] = 84;
         var3[85] = 85;
         var3[86] = 86;
         var3[87] = 87;
         var3[88] = 88;
         var3[89] = 89;
         var3[90] = 90;
         var3[91] = 91;
         var3[92] = 92;
         var3[93] = 93;
         var3[94] = 94;
         var3[95] = 95;
         var3[96] = 96;
         var3[97] = 97;
         var3[98] = 98;
         var3[99] = 99;
         var3[100] = 100;
         var3[101] = 101;
         var3[102] = 102;
         var3[103] = 103;
         var3[104] = 104;
         var3[105] = 105;
         var3[106] = 106;
         var3[107] = 107;
         var3[108] = 108;
         String[] var4;
         (var4 = new String[109])[0] = "alGetError";
         var4[1] = "alGetErrorDirect";
         var4[2] = "alEnable";
         var4[3] = "alEnableDirect";
         var4[4] = "alDisable";
         var4[5] = "alDisableDirect";
         var4[6] = "alIsEnabled";
         var4[7] = "alIsEnabledDirect";
         var4[8] = "alGetBoolean";
         var4[9] = "alGetBooleanDirect";
         var4[10] = "alGetInteger";
         var4[11] = "alGetIntegerDirect";
         var4[12] = "alGetFloat";
         var4[13] = "alGetFloatDirect";
         var4[14] = "alGetDouble";
         var4[15] = "alGetDoubleDirect";
         var4[16] = "alGetBooleanv";
         var4[17] = "alGetBooleanvDirect";
         var4[18] = "alGetIntegerv";
         var4[19] = "alGetIntegervDirect";
         var4[20] = "alGetFloatv";
         var4[21] = "alGetFloatvDirect";
         var4[22] = "alGetDoublev";
         var4[23] = "alGetDoublevDirect";
         var4[24] = "alGetString";
         var4[25] = "alGetStringDirect";
         var4[26] = "alDistanceModel";
         var4[27] = "alDistanceModelDirect";
         var4[28] = "alDopplerFactor";
         var4[29] = "alDopplerFactorDirect";
         var4[30] = "alDopplerVelocity";
         var4[31] = "alListenerf";
         var4[32] = "alListenerfDirect";
         var4[33] = "alListeneri";
         var4[34] = "alListeneriDirect";
         var4[35] = "alListener3f";
         var4[36] = "alListener3fDirect";
         var4[37] = "alListenerfv";
         var4[38] = "alListenerfvDirect";
         var4[39] = "alGetListenerf";
         var4[40] = "alGetListenerfDirect";
         var4[41] = "alGetListeneri";
         var4[42] = "alGetListeneriDirect";
         var4[43] = "alGetListener3f";
         var4[44] = "alGetListener3fDirect";
         var4[45] = "alGetListenerfv";
         var4[46] = "alGetListenerfvDirect";
         var4[47] = "alGenSources";
         var4[48] = "alGenSourcesDirect";
         var4[49] = "alDeleteSources";
         var4[50] = "alDeleteSourcesDirect";
         var4[51] = "alIsSource";
         var4[52] = "alIsSourceDirect";
         var4[53] = "alSourcef";
         var4[54] = "alSourcefDirect";
         var4[55] = "alSource3f";
         var4[56] = "alSource3fDirect";
         var4[57] = "alSourcefv";
         var4[58] = "alSourcefvDirect";
         var4[59] = "alSourcei";
         var4[60] = "alSourceiDirect";
         var4[61] = "alGetSourcef";
         var4[62] = "alGetSourcefDirect";
         var4[63] = "alGetSource3f";
         var4[64] = "alGetSource3fDirect";
         var4[65] = "alGetSourcefv";
         var4[66] = "alGetSourcefvDirect";
         var4[67] = "alGetSourcei";
         var4[68] = "alGetSourceiDirect";
         var4[69] = "alGetSourceiv";
         var4[70] = "alGetSourceivDirect";
         var4[71] = "alSourceQueueBuffers";
         var4[72] = "alSourceQueueBuffersDirect";
         var4[73] = "alSourceUnqueueBuffers";
         var4[74] = "alSourceUnqueueBuffersDirect";
         var4[75] = "alSourcePlay";
         var4[76] = "alSourcePlayDirect";
         var4[77] = "alSourcePause";
         var4[78] = "alSourcePauseDirect";
         var4[79] = "alSourceStop";
         var4[80] = "alSourceStopDirect";
         var4[81] = "alSourceRewind";
         var4[82] = "alSourceRewindDirect";
         var4[83] = "alSourcePlayv";
         var4[84] = "alSourcePlayvDirect";
         var4[85] = "alSourcePausev";
         var4[86] = "alSourcePausevDirect";
         var4[87] = "alSourceStopv";
         var4[88] = "alSourceStopvDirect";
         var4[89] = "alSourceRewindv";
         var4[90] = "alSourceRewindvDirect";
         var4[91] = "alGenBuffers";
         var4[92] = "alGenBuffersDirect";
         var4[93] = "alDeleteBuffers";
         var4[94] = "alDeleteBuffersDirect";
         var4[95] = "alIsBuffer";
         var4[96] = "alIsBufferDirect";
         var4[97] = "alGetBufferf";
         var4[98] = "alGetBufferfDirect";
         var4[99] = "alGetBufferi";
         var4[100] = "alGetBufferiDirect";
         var4[101] = "alBufferData";
         var4[102] = "alBufferDataDirect";
         var4[103] = "alGetEnumValue";
         var4[104] = "alGetEnumValueDirect";
         var4[105] = "alGetProcAddress";
         var4[106] = "alGetProcAddressDirect";
         var4[107] = "alIsExtensionPresent";
         var4[108] = "alIsExtensionPresentDirect";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "OpenAL10");
      }
   }

   private static boolean check_AL11(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("OpenAL11")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         (var3 = new int[36])[0] = 109;
         var3[1] = 110;
         var3[2] = 111;
         var3[3] = 112;
         var3[4] = 113;
         var3[5] = 114;
         var3[6] = 115;
         var3[7] = 116;
         var3[8] = 117;
         var3[9] = 118;
         var3[10] = 119;
         var3[11] = 120;
         var3[12] = 121;
         var3[13] = 122;
         var3[14] = 123;
         var3[15] = 124;
         var3[16] = 125;
         var3[17] = 126;
         var3[18] = 127;
         var3[19] = 128;
         var3[20] = 129;
         var3[21] = 130;
         var3[22] = 131;
         var3[23] = 132;
         var3[24] = 133;
         var3[25] = 134;
         var3[26] = 135;
         var3[27] = 136;
         var3[28] = 137;
         var3[29] = 138;
         var3[30] = 139;
         var3[31] = 140;
         var3[32] = 141;
         var3[33] = 142;
         var3[34] = 143;
         var3[35] = 144;
         String[] var4;
         (var4 = new String[36])[0] = "alListener3i";
         var4[1] = "alListener3iDirect";
         var4[2] = "alGetListener3i";
         var4[3] = "alGetListener3iDirect";
         var4[4] = "alGetListeneriv";
         var4[5] = "alGetListenerivDirect";
         var4[6] = "alSource3i";
         var4[7] = "alSource3iDirect";
         var4[8] = "alGetSource3i";
         var4[9] = "alGetSource3iDirect";
         var4[10] = "alListeneriv";
         var4[11] = "alListenerivDirect";
         var4[12] = "alSourceiv";
         var4[13] = "alSourceivDirect";
         var4[14] = "alBufferf";
         var4[15] = "alBufferfDirect";
         var4[16] = "alBuffer3f";
         var4[17] = "alBuffer3fDirect";
         var4[18] = "alBufferfv";
         var4[19] = "alBufferfvDirect";
         var4[20] = "alBufferi";
         var4[21] = "alBufferiDirect";
         var4[22] = "alBuffer3i";
         var4[23] = "alBuffer3iDirect";
         var4[24] = "alBufferiv";
         var4[25] = "alBufferivDirect";
         var4[26] = "alGetBuffer3i";
         var4[27] = "alGetBuffer3iDirect";
         var4[28] = "alGetBufferiv";
         var4[29] = "alGetBufferivDirect";
         var4[30] = "alGetBuffer3f";
         var4[31] = "alGetBuffer3fDirect";
         var4[32] = "alGetBufferfv";
         var4[33] = "alGetBufferfvDirect";
         var4[34] = "alSpeedOfSound";
         var4[35] = "alSpeedOfSoundDirect";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "OpenAL11");
      }
   }

   private static boolean check_EXT_debug(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_EXT_debug")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         (var3 = new int[20])[0] = 145;
         var3[1] = 146;
         var3[2] = 147;
         var3[3] = 148;
         var3[4] = 149;
         var3[5] = 150;
         var3[6] = 151;
         var3[7] = 152;
         var3[8] = 153;
         var3[9] = 154;
         var3[10] = 155;
         var3[11] = 156;
         var3[12] = 157;
         var3[13] = 158;
         var3[14] = 159;
         var3[15] = 160;
         var3[16] = 161;
         var3[17] = 162;
         var3[18] = 163;
         var3[19] = 164;
         String[] var4;
         (var4 = new String[20])[0] = "alDebugMessageCallbackEXT";
         var4[1] = "alDebugMessageCallbackDirectEXT";
         var4[2] = "alDebugMessageInsertEXT";
         var4[3] = "alDebugMessageInsertDirectEXT";
         var4[4] = "alDebugMessageControlEXT";
         var4[5] = "alDebugMessageControlDirectEXT";
         var4[6] = "alPushDebugGroupEXT";
         var4[7] = "alPushDebugGroupDirectEXT";
         var4[8] = "alPopDebugGroupEXT";
         var4[9] = "alPopDebugGroupDirectEXT";
         var4[10] = "alGetDebugMessageLogEXT";
         var4[11] = "alGetDebugMessageLogDirectEXT";
         var4[12] = "alObjectLabelEXT";
         var4[13] = "alObjectLabelDirectEXT";
         var4[14] = "alGetObjectLabelEXT";
         var4[15] = "alGetObjectLabelDirectEXT";
         var4[16] = "alGetPointerEXT";
         var4[17] = "alGetPointerDirectEXT";
         var4[18] = "alGetPointervEXT";
         var4[19] = "alGetPointervDirectEXT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_EXT_debug");
      }
   }

   private static boolean check_EXT_EFX(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("ALC_EXT_EFX")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         (var3 = new int[66])[0] = 165;
         var3[1] = 166;
         var3[2] = 167;
         var3[3] = 168;
         var3[4] = 169;
         var3[5] = 170;
         var3[6] = 171;
         var3[7] = 172;
         var3[8] = 173;
         var3[9] = 174;
         var3[10] = 175;
         var3[11] = 176;
         var3[12] = 177;
         var3[13] = 178;
         var3[14] = 179;
         var3[15] = 180;
         var3[16] = 181;
         var3[17] = 182;
         var3[18] = 183;
         var3[19] = 184;
         var3[20] = 185;
         var3[21] = 186;
         var3[22] = 187;
         var3[23] = 188;
         var3[24] = 189;
         var3[25] = 190;
         var3[26] = 191;
         var3[27] = 192;
         var3[28] = 193;
         var3[29] = 194;
         var3[30] = 195;
         var3[31] = 196;
         var3[32] = 197;
         var3[33] = 198;
         var3[34] = 199;
         var3[35] = 200;
         var3[36] = 201;
         var3[37] = 202;
         var3[38] = 203;
         var3[39] = 204;
         var3[40] = 205;
         var3[41] = 206;
         var3[42] = 207;
         var3[43] = 208;
         var3[44] = 209;
         var3[45] = 210;
         var3[46] = 211;
         var3[47] = 212;
         var3[48] = 213;
         var3[49] = 214;
         var3[50] = 215;
         var3[51] = 216;
         var3[52] = 217;
         var3[53] = 218;
         var3[54] = 219;
         var3[55] = 220;
         var3[56] = 221;
         var3[57] = 222;
         var3[58] = 223;
         var3[59] = 224;
         var3[60] = 225;
         var3[61] = 226;
         var3[62] = 227;
         var3[63] = 228;
         var3[64] = 229;
         var3[65] = 230;
         String[] var4;
         (var4 = new String[66])[0] = "alGenEffects";
         var4[1] = "alGenEffectsDirect";
         var4[2] = "alDeleteEffects";
         var4[3] = "alDeleteEffectsDirect";
         var4[4] = "alIsEffect";
         var4[5] = "alIsEffectDirect";
         var4[6] = "alEffecti";
         var4[7] = "alEffectiDirect";
         var4[8] = "alEffectiv";
         var4[9] = "alEffectivDirect";
         var4[10] = "alEffectf";
         var4[11] = "alEffectfDirect";
         var4[12] = "alEffectfv";
         var4[13] = "alEffectfvDirect";
         var4[14] = "alGetEffecti";
         var4[15] = "alGetEffectiDirect";
         var4[16] = "alGetEffectiv";
         var4[17] = "alGetEffectivDirect";
         var4[18] = "alGetEffectf";
         var4[19] = "alGetEffectfDirect";
         var4[20] = "alGetEffectfv";
         var4[21] = "alGetEffectfvDirect";
         var4[22] = "alGenFilters";
         var4[23] = "alGenFiltersDirect";
         var4[24] = "alDeleteFilters";
         var4[25] = "alDeleteFiltersDirect";
         var4[26] = "alIsFilter";
         var4[27] = "alIsFilterDirect";
         var4[28] = "alFilteri";
         var4[29] = "alFilteriDirect";
         var4[30] = "alFilteriv";
         var4[31] = "alFilterivDirect";
         var4[32] = "alFilterf";
         var4[33] = "alFilterfDirect";
         var4[34] = "alFilterfv";
         var4[35] = "alFilterfvDirect";
         var4[36] = "alGetFilteri";
         var4[37] = "alGetFilteriDirect";
         var4[38] = "alGetFilteriv";
         var4[39] = "alGetFilterivDirect";
         var4[40] = "alGetFilterf";
         var4[41] = "alGetFilterfDirect";
         var4[42] = "alGetFilterfv";
         var4[43] = "alGetFilterfvDirect";
         var4[44] = "alGenAuxiliaryEffectSlots";
         var4[45] = "alGenAuxiliaryEffectSlotsDirect";
         var4[46] = "alDeleteAuxiliaryEffectSlots";
         var4[47] = "alDeleteAuxiliaryEffectSlotsDirect";
         var4[48] = "alIsAuxiliaryEffectSlot";
         var4[49] = "alIsAuxiliaryEffectSlotDirect";
         var4[50] = "alAuxiliaryEffectSloti";
         var4[51] = "alAuxiliaryEffectSlotiDirect";
         var4[52] = "alAuxiliaryEffectSlotiv";
         var4[53] = "alAuxiliaryEffectSlotivDirect";
         var4[54] = "alAuxiliaryEffectSlotf";
         var4[55] = "alAuxiliaryEffectSlotfDirect";
         var4[56] = "alAuxiliaryEffectSlotfv";
         var4[57] = "alAuxiliaryEffectSlotfvDirect";
         var4[58] = "alGetAuxiliaryEffectSloti";
         var4[59] = "alGetAuxiliaryEffectSlotiDirect";
         var4[60] = "alGetAuxiliaryEffectSlotiv";
         var4[61] = "alGetAuxiliaryEffectSlotivDirect";
         var4[62] = "alGetAuxiliaryEffectSlotf";
         var4[63] = "alGetAuxiliaryEffectSlotfDirect";
         var4[64] = "alGetAuxiliaryEffectSlotfv";
         var4[65] = "alGetAuxiliaryEffectSlotfvDirect";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "ALC_EXT_EFX");
      }
   }

   private static boolean check_EXT_STATIC_BUFFER(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_EXT_STATIC_BUFFER")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[2];
         var10002[0] = 231;
         var10002[1] = 232;
         String[] var4;
         String[] var5 = var4 = new String[2];
         var5[0] = "alBufferDataStatic";
         var5[1] = "alBufferDataStaticDirect";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_EXT_STATIC_BUFFER");
      }
   }

   private static boolean check_SOFT_buffer_samples(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_buffer_samples")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[4];
         var10002[0] = 233;
         var10002[1] = 234;
         var10002[2] = 235;
         var10002[3] = 236;
         String[] var4;
         String[] var5 = var4 = new String[4];
         var5[0] = "alBufferSamplesSOFT";
         var5[1] = "alBufferSubSamplesSOFT";
         var5[2] = "alGetBufferSamplesSOFT";
         var5[3] = "alIsBufferFormatSupportedSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_buffer_samples");
      }
   }

   private static boolean check_SOFT_buffer_sub_data(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_buffer_sub_data")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[2];
         var10002[0] = 237;
         var10002[1] = 238;
         String[] var4;
         String[] var5 = var4 = new String[2];
         var5[0] = "alBufferSubDataSOFT";
         var5[1] = "alBufferSubDataDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_buffer_sub_data");
      }
   }

   private static boolean check_SOFT_callback_buffer(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_callback_buffer")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[8];
         var10002[0] = 239;
         var10002[1] = 240;
         var10002[2] = 241;
         var10002[3] = 242;
         var10002[4] = 243;
         var10002[5] = 244;
         var10002[6] = 245;
         var10002[7] = 246;
         String[] var4;
         String[] var5 = var4 = new String[8];
         var5[0] = "alBufferCallbackSOFT";
         var5[1] = "alBufferCallbackDirectSOFT";
         var5[2] = "alGetBufferPtrSOFT";
         var5[3] = "alGetBufferPtrDirectSOFT";
         var5[4] = "alGetBuffer3PtrSOFT";
         var5[5] = "alGetBuffer3PtrDirectSOFT";
         var5[6] = "alGetBufferPtrvSOFT";
         var5[7] = "alGetBufferPtrvDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_callback_buffer");
      }
   }

   private static boolean check_SOFT_deferred_updates(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_deferred_updates")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[4];
         var10002[0] = 247;
         var10002[1] = 248;
         var10002[2] = 249;
         var10002[3] = 250;
         String[] var4;
         String[] var5 = var4 = new String[4];
         var5[0] = "alDeferUpdatesSOFT";
         var5[1] = "alDeferUpdatesDirectSOFT";
         var5[2] = "alProcessUpdatesSOFT";
         var5[3] = "alProcessUpdatesDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_deferred_updates");
      }
   }

   private static boolean check_SOFT_events(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_events")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[8];
         var10002[0] = 251;
         var10002[1] = 252;
         var10002[2] = 253;
         var10002[3] = 254;
         var10002[4] = 255;
         var10002[5] = 256;
         var10002[6] = 257;
         var10002[7] = 258;
         String[] var4;
         String[] var5 = var4 = new String[8];
         var5[0] = "alEventControlSOFT";
         var5[1] = "alEventControlDirectSOFT";
         var5[2] = "alEventCallbackSOFT";
         var5[3] = "alEventCallbackDirectSOFT";
         var5[4] = "alGetPointerSOFT";
         var5[5] = "alGetPointerDirectSOFT";
         var5[6] = "alGetPointervSOFT";
         var5[7] = "alGetPointervDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_events");
      }
   }

   private static boolean check_SOFT_source_latency(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_source_latency")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         (var3 = new int[24])[0] = 259;
         var3[1] = 260;
         var3[2] = 261;
         var3[3] = 262;
         var3[4] = 263;
         var3[5] = 264;
         var3[6] = 265;
         var3[7] = 266;
         var3[8] = 267;
         var3[9] = 268;
         var3[10] = 269;
         var3[11] = 270;
         var3[12] = 271;
         var3[13] = 272;
         var3[14] = 273;
         var3[15] = 274;
         var3[16] = 275;
         var3[17] = 276;
         var3[18] = 277;
         var3[19] = 278;
         var3[20] = 279;
         var3[21] = 280;
         var3[22] = 281;
         var3[23] = 282;
         String[] var4;
         (var4 = new String[24])[0] = "alSourcedSOFT";
         var4[1] = "alSourcedDirectSOFT";
         var4[2] = "alSource3dSOFT";
         var4[3] = "alSource3dDirectSOFT";
         var4[4] = "alSourcedvSOFT";
         var4[5] = "alSourcedvDirectSOFT";
         var4[6] = "alGetSourcedSOFT";
         var4[7] = "alGetSourcedDirectSOFT";
         var4[8] = "alGetSource3dSOFT";
         var4[9] = "alGetSource3dDirectSOFT";
         var4[10] = "alGetSourcedvSOFT";
         var4[11] = "alGetSourcedvDirectSOFT";
         var4[12] = "alSourcei64SOFT";
         var4[13] = "alSourcei64DirectSOFT";
         var4[14] = "alSource3i64SOFT";
         var4[15] = "alSource3i64DirectSOFT";
         var4[16] = "alSourcei64vSOFT";
         var4[17] = "alSourcei64vDirectSOFT";
         var4[18] = "alGetSourcei64SOFT";
         var4[19] = "alGetSourcei64DirectSOFT";
         var4[20] = "alGetSource3i64SOFT";
         var4[21] = "alGetSource3i64DirectSOFT";
         var4[22] = "alGetSourcei64vSOFT";
         var4[23] = "alGetSourcei64vDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_source_latency");
      }
   }

   private static boolean check_SOFT_source_resampler(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_source_resampler")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[2];
         var10002[0] = 283;
         var10002[1] = 284;
         String[] var4;
         String[] var5 = var4 = new String[2];
         var5[0] = "alGetStringiSOFT";
         var5[1] = "alGetStringiDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_source_resampler");
      }
   }

   private static boolean check_SOFT_source_start_delay(FunctionProvider var0, PointerBuffer var1, Set var2) {
      if (!var2.contains("AL_SOFT_source_start_delay")) {
         return false;
      } else {
         FunctionProvider var10000 = var0;
         PointerBuffer var10001 = var1;
         int[] var3;
         int[] var10002 = var3 = new int[4];
         var10002[0] = 285;
         var10002[1] = 286;
         var10002[2] = 287;
         var10002[3] = 288;
         String[] var4;
         String[] var5 = var4 = new String[4];
         var5[0] = "alSourcePlayAtTimeSOFT";
         var5[1] = "alSourcePlayAtTimeDirectSOFT";
         var5[2] = "alSourcePlayAtTimevSOFT";
         var5[3] = "alSourcePlayAtTimevDirectSOFT";
         return Checks.checkFunctions(var10000, var10001, var3, var4) || Checks.reportMissing("AL", "AL_SOFT_source_start_delay");
      }
   }

   public PointerBuffer getAddressBuffer() {
      return this.addresses;
   }
}
