package cn.pokemmo.audio.playback;

import f.*;

public abstract class AudioChannelMixerContext {
    public static final com9__4 kK0;
    public static final com9__4 I1;
    public static final com9__4 Rt;
    public static final com9__4 iN;
    public static final com9__4 yI;
    public static final com9__4 CL;
    public static final com9__4 Sx;
    public static final com9__4 PZ;
    public static final com9__4 Q8;
    public static final com9__4 cu0;
    public static final com9__4 Hb;
    public static final com9__4 kK;
    public static final com9__4 sg;
    public static final com9__4 ad0;
    public static final com9__4 aO;
    public static final com9__4 sl;
    public static final com9__4 Gp0;
    public static final com9__4 fA;
    public static final com9__4 coM1;
    public static final com9__4 h1;
    public static final com9__4 HI0;
    public static final com9__4 n50;
    public static final com9__4 DQ;
    public static final com9__4 jd0;
    public static final com9__4 On0;
    public static final com9__4 xm;
    public static final com9__4 fJ0;
    public static final com9__4 DA0;
    public static final com9__4 rk0;
    public static final com9__4 Up0;
    public static final com9__4 qk;
    public static final com9__4 Be0;
    public static final com9__4 xN;
    public static final com9__4 am;
    public static final com9__4 I20;
    public static final com9__4 k7;
    public static final com9__4 oj0;
    public static final com9__4 mL;
    public static final com9__4 Vg;
    public static final com9__4 Rs0;

    static {
        kK0 = new com9__4("u_projTrans");
        I1 = new com9__4("u_viewTrans");
        Rt = new com9__4("u_projViewTrans");
        iN = new com9__4("u_cameraPosition");
        yI = new com9__4("u_cameraDirection");
        CL = new com9__4("u_cameraUp");
        Sx = new com9__4("u_cameraNearFar");
        PZ = new com9__4("u_worldTrans");
        Q8 = new com9__4("u_viewWorldTrans");
        cu0 = new com9__4("u_projViewWorldTrans");
        Hb = new com9__4("u_normalMatrix");
        kK = new com9__4("u_bones");
        sg = new com9__4("u_shininess", mb0_2.an0);
        ad0 = new com9__4("u_opacity", sh_0.vF0);
        aO = new com9__4("u_diffuseColor", PRN_.Ly);
        sl = new com9__4("u_diffuseTexture", mz_2.g7);
        Gp0 = new com9__4("u_diffuseUVTransform", mz_2.g7);
        fA = new com9__4("u_specularColor", PRN_.zz);
        coM1 = new com9__4("u_specularTexture", mz_2.GB0);
        h1 = new com9__4("u_specularUVTransform", mz_2.GB0);
        HI0 = new com9__4("u_emissiveColor", PRN_.sI);
        n50 = new com9__4("u_emissiveTexture", mz_2.protected$);
        DQ = new com9__4("u_emissiveUVTransform", mz_2.protected$);
        jd0 = new com9__4("u_reflectionColor", PRN_.Ar);
        On0 = new com9__4("u_reflectionTexture", mz_2.Dh0);
        xm = new com9__4("u_reflectionUVTransform", mz_2.Dh0);
        fJ0 = new com9__4("u_normalTexture", mz_2.yS);
        DA0 = new com9__4("u_normalUVTransform", mz_2.yS);
        rk0 = new com9__4("u_ambientTexture", mz_2.cW);
        Up0 = new com9__4("u_ambientUVTransform", mz_2.cW);
        qk = new com9__4("u_alphaTest");
        Be0 = new com9__4("u_overlayColor", Rv0.XT);
        xN = new com9__4("glowColor", na0_0.UG);
        am = new com9__4("glowIntensity");
        I20 = new com9__4("glowThreshold");
        k7 = new com9__4("glowSize");
        oj0 = new com9__4("glowTexSize");
        mL = new com9__4("glowInvTexSize");
        Vg = new com9__4("u_ambientCubemap");
        new com9__4("u_dirLights");
        new com9__4("u_pointLights");
        new com9__4("u_spotLights");
        Rs0 = new com9__4("u_environmentCubemap");
    }
}
